### ISSUE TITLE
dataRetrieval: readWQP

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#106]
Parent: dataRetrieval: accessing timeseries data

- Available functions for pulling WQP data
- Parameters available to specify location, time span, and type of data
- Exploring metadata
- Examples

**Comment by lindsaycarr** [comment]
date: "9999-10-31"

**Comment by lindsaycarr** [comment]
@ldecicco-USGS have you reviewed this lesson and are we good to close this?

**Comment by ldecicco-USGS** [comment]
Ah, looking now...no, I think we should clean it up a bit. At a minimum, taking out looking at the entire siteInfo attribute. I'll try to do something now.

**Comment by lindsaycarr** [comment]
:+1:

**Comment by ldecicco-USGS** [comment]
Table2 uses the `arg_table_functions.R`, but one of the descriptions as a (rather important) link. I don't have time right now to figure out if we can pull that out automagically, but something to think about.

**Comment by lindsaycarr** [comment]
Not sure I understand what you're saying here. It has a link and shouldn't? Or vice versa?

**Comment by ldecicco-USGS** [comment]
Vice versa...it says: "see for a complete list of options. A list of arguments can also be supplied." and in the help files, it says "see https://www.waterqualitydata.us/webservices_documentation for a complete list of options. A list of arguments can also be supplied."

**Comment by lindsaycarr** [comment]
@ldecicco-USGS would you still like to take out the siteInfo stuff before calling this done? Aren't we just looking at the lat and long of that attribute table?

**Comment by ldecicco-USGS** [comment]
I think I already took the siteInfo stuff out. It was spewwing out pages of a siteInfo dataframe print statement awhile back. It's all good now.

**Comment by lindsaycarr** [comment]
Ah gotcha! Thanks
