### ISSUE TITLE
geoknife: troubleshooting

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#110]
Parent: geoknife: accessing gridded data

Advanced geoknife features

- Diagnosing job problems

**Comment by lindsaycarr** [comment]
`date: "9999-08-31"`

**Comment by lindsaycarr** [comment]
@jiwalker-usgs trying to distinguish which of the following should go into #109 versus here. What are your thoughts? 

#109 will have a section on what the heck a `geojob` is, how to use `wait` and `email`, and then the final workflow for `geoknife` calls. All of these helper functions seem like they belong in troubleshooting. Am I missing anything else for troubleshooting?

```
check()
running()
error()
successful()
id()
cancel()
```

**Comment by jiwalker-usgs** [comment]
`check()` probably fits more in the normal workflow than troubleshooting, with `running()`, `error()`, and `successful()` as part of that.  I'd also suggest mentioning `wait()` along with these.  `id()` definitely belongs in troubleshooting as you end up digging in to more about the process.  We should be careful with `cancel()` as it doesn't actually cancel the process on the server, but just clears the state in the geojob.  What is mentioned should probably tie in with the troubleshooting.

**Comment by lindsaycarr** [comment]
After discussion with @jiwalker-usgs, we decided not to do the troubleshooting section. `id()` and `cancel()` were the only functions left. `id()` is meant to be used to recreate your geojob from its id so you can add new variables and re-run easily, but this feature isn't full established. `cancel()` sounds like it doesn't really do much and is more of a power-user feature.
