### ISSUE TITLE
sbtools: data discovery

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#113]
Parent: sbtools: accessing cloud-based data

Exploring available data

- Data browsing and searching through the ScienceBase web interface
- Data queries with the sbtools interface
- Leveraging the best of both interfaces

`9999-07-25`

**Comment by lindsaycarr** [comment]
@aappling-usgs do you have any idea what that 3rd bullet might be referring to? I can't remember the motivation for that.

**Comment by aappling-usgs** [comment]
Hmm...maybe just showing how you can get the URL to an item from sbtools, then follow that URL to browse in the web interface? can be helpful if there are maps or metadata to view, and/or to check or repair an sb item if any of the sbtools-based POST commands might have failed

**Comment by lindsaycarr** [comment]
@aappling-usgs what's the difference between the `query_sb_*` functions and the `query_items_*` functions? Seems like `query_sb` also returns items.

**Comment by lindsaycarr** [comment]
`9999-07-25`

**Comment by aappling-usgs** [comment]
could just be inconsistent naming/output. sciencebase is down tonight (or maybe my hotel internet is funky?) so I can't double check, but the sbtools paper shows `query_item_identifier` producing a data.frame, whereas `query_item_in_folder` and `query_sb_*` return lists of sbitems (or single items?). i don't think there's a way to use `query_sb_*` to search for items within a folder, as `query_item_in_folder` does.

**Comment by lindsaycarr** [comment]
are people actually using SB as a way to find data? Is this totally unnecessary?

**Comment by aappling-usgs** [comment]
you ask this after writing a beautiful lesson on the topic =). i doubt that the query potential has been fully realized, but i hope that your lesson turns into someone thinking of a great dataset mining project someday (could even be us?). in the meantime, i absolutely use `query_item_in_folder` and `query_item_identifier` and possibly some others in the metabolism synthesis project - querying is clearly useful when looking for one's own files.

**Comment by lindsaycarr** [comment]
Ha I know, but Laura brought it up and I thought it was worth mentioning. I just kind of looked at the functions available and started going. Realized I should have done a little more checking on whether or not they were all important. 

Glad this was not completely useless and will still be good to show new users!

**Comment by lindsaycarr** [comment]
Link for what categories & types are available:
