### ISSUE TITLE
sbtools: getting data

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#114]
Parent: sbtools: accessing cloud-based data

Retrieving data

- Inspecting and downloading files
- Using ScienceBase's web feature services to visualize spatial data

`9999-07-01`

**Comment by lindsaycarr** [comment]
# general sb interaction info
`authenticate_sb`
`current_session`
`is_logged_in`
`sb_ping`
`session_details`
`session_logout`
`session_renew`
`session_validate`
`set_endpoint`
`user_id`

# sbitems & downloading data
`identifier_exists`
`is.sbitem`
`item_exists`
`item_get`
`item_get_fields`
`item_get_parent`
`item_get_wfs`
`item_list_children`
`item_list_files`
`sbitem`

**Comment by aappling-usgs** [comment]
This looks like a good high-level organization of the information.

Are there any uncommonly used SB interaction methods you can omit, or just list briefly? `sb_ping`, `set_endpoint`, and `session_validate` are candidates. Seems like help with focus could be more valuable than an exhaustive catalog. also, `session_details` appears to be more or less redundant with `is_logged_in`, at least for the time being.

for the second section, i bet generic `item_get` will fit best after all the specific `item_get_...` functions. it would be great if you could talk about when you'd want to use `identifier_exists` vs `item_exists`, `item_get` vs `as.sbitem`. `sbitem` and `is.sbitem` probably go well together. but all this will probably become obvious as you're fleshing out the lesson.

**Comment by lindsaycarr** [comment]
Yeah, I think we can exclude some of those less common functions. Do you think we should include a section on using `authenticate_sb` not interactively, where you save your password info somewhere locally? Seems like people would have a use for this, but I don't want to promote something that's not recommended.

**Comment by aappling-usgs** [comment]
hmm, good Q; leaning toward 'no'. i wish `sbtools` had built-in functionality for this; then, i'd be all for including it here. there will definitely be people for whom this is useful. while our solutions are not bad, they're not yet watertight, either. maybe avoid mentioning it for now, create an `sbtools` Issue for it, and share our approaches openly but only with caveats and with students who ask directly about it? maybe @jiwalker-usgs or @jread-usgs has an opinion?

**Comment by lindsaycarr** [comment]
@aappling-usgs where should we put a note about not pulling SB data in parallel?

**Comment by aappling-usgs** [comment]
closing thoughts?

**Comment by aappling-usgs** [comment]
Here are ScienceBase's own, current words on being a good citizen (at https://www.sciencebase.gov/catalog/userAgreement/checkAgreement):

> **API Interaction and Programmatic Content Editing in ScienceBase**
> 
> In addition to the browser-based interface, ScienceBase also supports powerful API access and interaction via any programming language that can access and parse a JSON response on the web or software that uses both standard services (e.g., Open Geospatial Consortium services) and a REST interface. This type of use is permitted for all authorized users, and while not explicitly regulated, users are expected to adhere to practices of responsible use in accordance to web convention, government policy, and the guidance provided in this document and by the ScienceBase team. Actions that may compromise the system directly or for other users (e.g., very high volume file creation or access requests, etc.) may be temporarily suspended by ScienceBase staff if necessary, so that a more opportune time or approach for system use may be arranged.
 > 
> Please feel free to contact the ScienceBase team with any questions or for guidance related to advanced use. The ScienceBase team encourages innovative and collaborative uses for ScienceBase and will be happy to offer more targeted developer guidance and information on request.
