### ISSUE TITLE
bugs from NM

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/training-curriculum#150]
- [x] t.test in explore should be between estimated and approved, since other codes are now removed in clean
- [x] third lesson goals bullet in clean mentions base `merge()` but we don't use that anymore 
- [x] add s to http to GRAN repo in setup instructions
- [x] add better example of using dplyr joins using lat/lon data for the sites in intro_df. Delete the unnecessary csvs used for the current example @wdwatkins 
- [x] Change the example of using colClasses by explicitly naming each column. Don’t use NA, or at least pull it out into its own object (not nested inside read.csv). Explain it better then show the shortcut. @jiwalker-usgs 
- [x] Add note to Clean section on map about actually going through the Clean steps to get the cleaned up data. @lindsaycarr

**Comment by lindsaycarr** [comment]
@jiwalker-usgs column classes change? Is that happening soon?

**Comment by jiwalker-usgs** [comment]
Thanks for the reminder
