### ISSUE TITLE
Version control basics*

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#153]
1. Define version control and give examples of how it is useful.
2. Navigate the GitHub interface.
3. Summarize a typical GitHub-to-R workflow.

`date: "9999-10-31"`

**Comment by aappling-usgs** [comment]
http://swcarpentry.github.io/git-novice/ - probably too long, but could be nice as a reference to share

**Comment by lindsaycarr** [comment]
Already on the hook for summer institute, but less language specific. Could be good to share material. Most of this is version control in general, but ending shows how R and version control work well together.

Andrew Yan shared ppt w/ Lindsay recently. Talk with others on scrum (Mary Bucknell).

**Comment by lindsaycarr** [comment]
vignette for vizlab -- how to collaborate (assigning tasks/getting reviews)

**Comment by lindsaycarr** [comment]
When going through this section during the course, it should actually have people create a GitHub repo for a package, then make an RStudio project

**Comment by ldecicco-USGS** [comment]
I think we need to address SSH. At a minimum, something like:

![2017-05-11_13-26-19](https://cloud.githubusercontent.com/assets/1105215/25965487/c24852cc-364d-11e7-96d3-4dd25fe6fd35.png)

This is a constant source of frustration for the occasional USGS git user.

**Comment by lindsaycarr** [comment]
I was under the impression we said this would go in the package mechanics section? Maybe not...I'd need to look at our meeting notes.

**Comment by ldecicco-USGS** [comment]
It's such a frustrating and common issue, and this page will (hopefully) be used as a git reference...I think it should be mentioned in both places. Note, I'm not describing how to set up your SSH keys or add the DOI root cert to devtools....just make sure they pick SSH and hot HTTPS

The more we emphasize these pain points, the less we have to troubleshoot later

**Comment by lindsaycarr** [comment]
Ah I see! Then yes, will add

**Comment by ldecicco-USGS** [comment]
Along with the addition to tell people to use SSH, I think you should edit the nice diagram you made. The top cloud says "Master Repository". I think using the word "Master" will end up getting confusing because "Master" in every other aspect of git refers to a branch/branching. I'd just change it to "Upstream Repository" or "Canonical Repository" (but my preference is "Upstream")

**Comment by ldecicco-USGS** [comment]
Another specific thing to change would be (ack...I can't do line references on .Rmd files? lame):

```
git remote add upstream https://github.com/USGS-R/dataRetrieval
```

Make sure that is changed to:
```
git remote add upstream git@github.com:USGS-R/dataRetrieval.git
```

**Comment by lindsaycarr** [comment]
Content complete, further feedback provided in #206
