### ISSUE TITLE
Writing tests⁺

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#155]
1. Describe the importance of tests.
2. Explain test-driven development.
3. Construct and execute simple tests using the testthat package.

`date: "9999-08-31"`

**Comment by lindsaycarr** [comment]
- different types of tests: functional, unit, data, integration, etc
- define all types, maybe only cover a couple in actual course (unit, integration)
- continuous integration/travis (here or in #157)

**Comment by ldecicco-USGS** [comment]
Even though many (or any?) of us has used this....we might want to do a quick survey of the `assertr` package...it seems to be super-popular with the rOpenSci folks:

https://github.com/ropensci/assertr

**Comment by wdwatkins** [comment]
Yeah I used that a bit in the analytics viz.  Seems useful for adding tests/assertions in more script-y use cases.

**Comment by aappling-usgs** [comment]
it's mentioned very briefly in defensive programming...

**Comment by lindsaycarr** [comment]
code coverage -- needs more content

**Comment by lindsaycarr** [comment]
Content complete, further feedback provided in #206
