### ISSUE TITLE
Maintenance*

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#157]
1. Identify requirements of package maintenance. 
2. Organize tasks on GitHub in Milestones and Projects.
3. Reference tasks in GitHub Pull Requests and Issues. 
4. Use reviewer requests on GitHub.
5. Describe process to update packages on GRAN.

`date: "9999-06-30"`

**Comment by lindsaycarr** [comment]
- dependency management/bloat (too many dependencies = hidden maintenance costs)
- dependency trees

**Comment by lindsaycarr** [comment]
Is this where debugging should go?

**Comment by ldecicco-USGS** [comment]
I'd vote make it it's own thing, and if the 2 topics are short enough, they could merge into 1 topic, but if not, they could both be stand-alone.

**Comment by aappling-usgs** [comment]
Agreed with @ldecicco-USGS - if possible, make it super obvious by giving it its own title - this is possibly a  section that people will return to repeatedly over the following few months, so should be easy to find.

**Comment by lindsaycarr** [comment]
needs to mention rhub per #208
