### ISSUE TITLE
better code chunk styling

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#163]
It would be great if our Hugo code chunks were styled more like RStudio code. Seems arbitrary right now. This would be desired across the entire Hugo curriculum, but might be able to fit in with the tasks/budget for this DL course.

![image](https://cloud.githubusercontent.com/assets/13220910/24426409/37cf97f6-13cd-11e7-8b06-c41bd23c0c3c.png)

Why are "read" and "stat" red?

**Comment by ldecicco-USGS** [comment]
I'd try to follow gitHub's "r" styling. There's a ton more that github does that we don't do for code style. I think we hit some, but not all...

**Comment by lindsaycarr** [comment]
@mwernimont this is especially important for passing 508 standards. None of our current code blocks, code tags, or in-line links do not have have enough contrast with the background.

**Comment by mwernimont** [comment]
@lindsaycarr so not really sure what parts need to be changed and what is good at the moment, any clarity possible?

**Comment by lindsaycarr** [comment]
I'm not super sure of all the changes that would be needed myself, but I do know that there is not reason `stat` and `read` in the snippet above should be colored. R has specific syntax highlighting - I found [this CSS from RStudio](https://github.com/rstudio/rstudio/blob/master/src/cpp/session/resources/r_highlight.html). Does this help?

**Comment by lindsaycarr** [comment]
This stackoverflow comment has some potential resources for it: https://stackoverflow.com/questions/19999687/syntax-highlighting-rules-and-definitions

**Comment by lindsaycarr** [comment]
Not sure I follow exactly what you mean, but the code chunk styling is off for all the pages. I had assumed there was some underlying CSS used to specify how to style any code but maybe that's not the case.

**Comment by mwernimont** [comment]
I meant where to look at the site for the wrong colored code chunks.

**Comment by mwernimont** [comment]
![screen shot 2017-08-22 at 11 21 16 pm](https://user-images.githubusercontent.com/6390096/29576040-148b4cc2-872c-11e7-9972-38d7b0459b6f.png)

@lindsaycarr Do we want the **Read** to be this color? Its just a class certain thing get that I can make any color we want, just not sure what that is.

**Comment by lindsaycarr** [comment]
Sorry I never gave examples, my access to GitHub that day was nonexistent. But the screenshot you have there looks good to me. That's what I would expect to see. Can we merge your changes and then I can explore other examples on dev and see if anything else jumps out?

**Comment by mwernimont** [comment]
@lindsaycarr https://github.com/USGS-R/training-curriculum/pull/303

**Comment by lindsaycarr** [comment]
Hmmm what's strange is that it definitely fixed some of the code, but not all:

![image](https://user-images.githubusercontent.com/13220910/29668673-aa6fba18-88a6-11e7-890b-dd8493d047aa.png)

**Comment by lindsaycarr** [comment]
No thanks to the orange :)

The blue is good (and has good contrast for 508 compliance). The other style that needs to change is the inline code. The contrast is very poor and doesn't pass 508 standards.

![image](https://user-images.githubusercontent.com/13220910/29669078-eb4c2ab6-88a7-11e7-853b-059bc65a3ddb.png)

**Comment by mwernimont** [comment]
Alright, I can look into that, just making them black is fine?

**Comment by lindsaycarr** [comment]
Hmmmm I kind of like having them not black so that it stands out a bit more. Maybe a darker blue than what is there? I like the grey background, just need a darker text color to tell them apart.

**Comment by mwernimont** [comment]
Can do!

**Comment by mwernimont** [comment]
@lindsaycarr https://github.com/USGS-R/training-curriculum/pull/304

**Comment by lindsaycarr** [comment]
Closed by #318 and #319
