### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#174]
1. Track down the source of an error.
2. Understand the different ways of debugging (`browser`, `traceback`, breakpoints)
3. Learn how to use the different debug buttons in RStudio.

`date: "9999-04-30"`

**Comment by aappling-usgs** [comment]
http://adv-r.had.co.nz/Exceptions-Debugging.html#debugging-techniques

**Comment by lindsaycarr** [comment]
@wdwatkins https://github.com/USGS-R/lakeReport/blob/master/debugging.Rmd

**Comment by wdwatkins** [comment]
Will this go before or after testing?  I think it might make a good follow up to testing.

**Comment by lindsaycarr** [comment]
I think we only go as far as "we should have this be a stand-alone section". I think it makes sense to go after testing. It also makes sense after Maintenance since this touches on debugging issues that users may find.

**Comment by aappling-usgs** [comment]
Also note a couple of minor synergies with Defensive Programming, which mentions traceback() and the importance of good error messages to facilitate debugging. I don't think those minor overlaps require any particular lesson order, but we may want to add a few cross references once we have all the lessons drafted.

**Comment by ldecicco-USGS** [comment]
Here's a nice list of common Errors in R:

https://www.quantinsti.com/blog/common-errors-r/

Might be good to just include the link, or do something similar (here? defensive programming? somewhere else?)

**Comment by aappling-usgs** [comment]
good find! i think this would fit well in debugging

**Comment by lindsaycarr** [comment]
Content complete, further feedback provided in #206
