### ISSUE TITLE
Package mechanics

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#185]
Hadley’s package book - mostly link to this, but have outline here.
imports/dependencies
Philosophy - limiting dependency tree as a balancing act
Technical part, too
NAMESPACE
Data - data, extdata, sys.data (not big data/sbtools)
Package skeleton
Internal vs external functions
Obj: Define the required directories and files for a package.
Build, reload, check, test button
Do more talking/explaining here. Not a lot of action.
Licenses

**Comment by ldecicco-USGS** [comment]
Didn't get to "Internal vs external functions"...need to ....

**Comment by lindsaycarr** [comment]
objectives in "objective language"

1. List the structural components of an R-package.
2. Understand package dependency trees.
3. Be familiar with different ways data can be included in packages.
4. Correctly define what licenses and disclaimers are needed for USGS software. 
5. Apply the build and check features to a package.
6. Define internal functions and know their benefits.

**Comment by lindsaycarr** [comment]
This is at a finished point. See #206 for smaller corrections.
