### ISSUE TITLE
change repo name to training-curriculum

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#19]
if we start advanced or intermediate R material, it will live here also

**Comment by lindsaycarr** [comment]
@ldecicco-USGS can you change the name? We plan to have folders with intermediate, advanced, etc curriculum in the future and want the name to be more generic. I'm not sure how many downstream effects this has

**Comment by ldecicco-USGS** [comment]
OK, people will need to change their remotes.
