### ISSUE TITLE
Establish schedule

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#204]
@ldecicco-USGS, @jiwalker-usgs, @wdwatkins, @lindsaycarr, and @limnoliver met to discuss this schedule. Please comment with any concerns, or suggested changes. Each section should have at least one additional person besides the Facilitator. Add yourself to the ones you plan to sit in on (@lindsaycarr will plans to attend all of them since she is coordinating the week). 

We will be making a canned repository to allow people to practice many of these sections. See #205.

| Day | Start | End | Module | Facilitator | Floaters |
| --- | -- | -- | --- | --- | --- |
| Mon 6/5 | 09:00 am | 10:00 am | Welcome | @lindsaycarr |  |
| Mon 6/5 | 10:00 am | 11:30 am | What is a Package? | @ldecicco-USGS | @lindsaycarr |
| Mon 6/5 | 12:30 pm | 01:30 pm | Project Management | @eread-usgs | @lindsaycarr |
| Mon 6/5 | 01:30 pm | 05:00 pm | Package mechanics | @ldecicco-USGS | @lindsaycarr |
| Tue 6/6 | 09:00 am | 12:00 pm | Version control | @wdwatkins | @lindsaycarr |
| Tue 6/6 | 01:00 pm | 05:00 pm | Documentation | @lindsaycarr |  |
| Wed 6/7 | 09:00 am | 11:00 am | Debugging | @wdwatkins | @lindsaycarr |
| Wed 6/7 | 11:00 am | 02:00 pm | Defensive programming | @aappling-usgs | @lindsaycarr |
| Wed 6/7 | 02:00 pm | 04:00 pm | Writing tests | @jiwalker-usgs | @lindsaycarr |
| Thu 6/8 | 09:00 am | 10:00 am | Maintenance | @jread-usgs | @lindsaycarr |
| Thu 6/8 | 10:00 am | 05:00 pm | Application/practice | @lindsaycarr | @lindsaycarr |

**Comment by lindsaycarr** [comment]
Flexibility in practicing each section:

1. Work on "throw-away" package together w/ canned steps
2. Use time to work on their own pkg

**Comment by lindsaycarr** [comment]
package mechanics will have people build pkg locally
version control is where people will pull in our stock repo

**Comment by lindsaycarr** [comment]
canned example for final day to add a new feature where you do through all the steps; then people move on to their own work

**Comment by lindsaycarr** [comment]
project management should touch on CI, don't need to show how exactly to add CI (maybe just copy/paste from dataRetrieval???)

**Comment by lindsaycarr** [comment]
do a practice round for version control w/ locals since it is SOO SOO critical

**Comment by eread-usgs** [comment]
@lindsaycarr I'm happy to do a brief section on PM. However, I'm going to be wrapped up in another training until noon on Monday. Could you schedule the session, which likely will only last 30-45 mins, for after the lunch break (starting anytime after 12pm noon) on Monday? 

Thanks,
Emily

**Comment by lindsaycarr** [comment]
@eread-usgs moved lunch down a half hour and adjusted the time. Thanks!

**Comment by lindsaycarr** [comment]
The schedule has been approved by people attending. Closing the issue.
