### ISSUE TITLE
Feedback on finished sections

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#206]
I originally suggested adding these to the individual sections issues, but I think we should collect them here since we may or may not get to them before the course actually happens. You can edit this comment and add your feedback under each section.

[From Sam] FYI, I provided feedback on places that I felt a little lost or seemed to be potential sticky points. I tried to take authors or those who are presenting the material in places that I thought were more critical to the workshop. I did not provide editorial feedback as I thought this wasn't the most efficient way to give that feedback...

## What's a package?
**Suggested Changes** 
1.  In when/why to build a package, I think it would be nice to say that you don't HAVE to share a package, and that it can be useful just to package your own personal functions that you use often

## Package mechanics
**General notes** 
1. @ldecicco-USGS when I went through this section, I wanted more details on documentation up front. Maybe do a brief overview of documentation - for example, just showing all the different pieces of documentation within a preexisting package (help files, vignettes, etc). If attendees have no experience with documentation, this might be confusing without an overview. I think we talked about this at the last meeting - weaving in some documentation to package mechanics. Then maybe go into more detail on the pieces that you include here (specifically, function documentation with roxygen and the DESCRIPTION file). 

**Suggested Changes** 
1. Package Skeleton Step 2: Choose New Package Option -- Rstudio first gives me options of 'new directory', 'existing directory', or 'version control', so should add select "new directory', then user will get to the options currently listed in step 2
2. Package Skeleton Step 3: For me, the 'create git repository' was automatically checked. Do you want attendees to uncheck this? (example has it unchecked)
3. Minimum requirements: see general notes above. Maybe here you could fill out the description file with the students, since you reference here and elsewhere in the package mechanics section? Then in documentation, just reiterate you should modify this file. 
4. Data: would be nice for an overview of when/why you would want to include data in your package
5. Data: how would you normally find data in a random package? Do you have to search through documentation or is there a particular function/call that can help you discover data within a package?
6. Depending on other packages: this seems out of order with regard to what I said about: documentation being part of this section. I recommend going into documentation a bit more in Package Mechanics and the various bits you have weaved in. Alternatively, you could move this particular section to documentation.
7. Depending on other packages: I recommend using an example that doesn't require the NSE discussion -- this took me  afew minutes to wrap my head around, and still not sure I completely understand it. I think it's more confusion than it's worth. For example, when you say, 'Your first question might be...' -- mine was not related to the text `Date <- doy <- Flow <- ".dplyr.var"` but rather to the roxygen tags.  
8. License: This also feels like it could go in documentation.

## Version control
**General Feedback**
1. If the "project management" section is going to come before version control, I suggest you leave out all git-specific language. As I read through version control, I kept thinking that the topics in project management would be perfect weaved into version control or at the end of version control (how often should I commit? Submit a pull request?) 
2. @wdwatkins - In the workflow section, I think it would be super useful to incorporate an activity from the "demo" package that we talked about creating, where users fork, clone, make changes, submit pull requests, and pull from upstream (maybe even a few times). I have the hardest time getting comfortable with this workflow, and I'm guessing practice = closer to perfect! Additionally, the further down in this tutorial you get (stashing, branching, reviewing code changes), the more complex it gets and probably is new material for some of the attendees. If you can have attendees coding/experiencing all of these, I think it will help a lot! 

**Suggested Changes**
1. Definitely include SSH setup or links to appropriate help files. 
2. Canonical and upstream are used interchangeably - and I had to keep going back to the opening paragraphs to remember what this was referring to. Maybe pick one? Seems that canonical is used most in text, but upstream is used in the figure. Personally prefer "upstream repository". 
3. Submitting a pull request: the end of this section mentions waiting for your pull request to be merged. I think it would be nice to add what happens if you were to make changes in the meantime. Do they get added to the pull request? What happens if you submit a pull request, and then pull from upstream in the meantime and start working again? These are the parts that are really confusing to me!
4. Stashing: can you give an example of when you might want to use this feature? 
5. Reviewing code changes: this could maybe go into testing? Or a working example of this could go into testing? It's hard to conceptualize 'testing' the PR without having any framework for how you would test it. 

## Debugging
**Suggested Changes**
1. @wdwatkins when I run your example in the section "Debugging an unfamiliar function", I don't get the blue links to the code as you show in fig "error traceback" - just the list of functions. Does this only work if you've forked the repo and cloned it locally? The text suggests that you'll be able to do the tutorial just with `install.packages(dataRetrieval)` - maybe I'm missing something here? I can navigate to the function from the traceback panel but can't put add a breakpoint (I'm guessing because I'm not actually looking at the source?)

## Defensive programming
**Suggested Changes**
1. Common gotchas: it would be nice to have examples for the suggested functions to use instead (e.g., `isTRUE()` and `assert_that()`) to show how they would be implemented in a function. I got distracted because it wasn't immediately clear to me what those functions were doing or how I would implement them.
2. Fail conspicuously: like the comment above, it would be super useful to walk through examples of how to implement `conditions` - as it's a bit hard to conceptualize without seeing them within a function.
3.  I really like the examples in Fail Informatively - but it took me a while to wrap my head around what they were doing because it used so many unfamiliar commands (`tryCatch`, `switch`, `sprintf`), some of which are not related to defensive programming. Maybe simplify so no one gets caught up trying to understand the function itself? Probably fine in the online tutorial since people can take some time, but in a live training might struggle with it.
 
## Maintenance

not complete yet, so skip

## Writing tests
**General Feedback**
1. At a high level - I'm still sort of confused as to how the testing is implemented once the tests are written. Is the testing just used by the developers - or is it integrated somehow into the package? Is it completely separate from warnings/defensive programming? What is the suggested workflow for testing?

**Suggested Changes**
1. In 'What types of tests should I write?' -- is there a simple chunk of code that you can use as a foundation for examples of the different types of tests? I was having a hard time thinking of examples to contrast these -- and it really helped when you gave a BDD example later on. 
2. Not sure if you're going to go into any more detail about coverage -- but I was super interested in this and wanted to see an example of it implemented to create a badge on the README file. 

## Documentation
**Suggested Changes**
1. At the end of the vignettes section, and  beginning of README section, text is underlined where it looks like it is linked to something.

**Comment by wdwatkins** [comment]
Good catch on the debugging stuff @limnoliver, I'm usually running dataRetrieval from a local build from source.  I hadn't realized that made a difference.

**Comment by lindsaycarr** [comment]
Major things: 

1. Documentation vs Package mechanics
2. Should we get into NSE in package mechanics?
3. Project mgmt vs version control
4. Simplify examples used in defensive programming (probably good note overall)
5. Need high-level "testing" explanation
6. More examples in "testing"

**Comment by lindsaycarr** [comment]
Not introducing NSE,means people will likely have warnings/notes in pkg check when using dplyr. That is the point of introducing NSE. Be clear about goal with showing it. Example to explain NSE: `library(dataRetrieval)` -- package name not quoted.

**Comment by lindsaycarr** [comment]
Created smaller, digestable issues from the things listed here that have not already been addressed. Thanks @limnoliver for your work on this!
