### ISSUE TITLE
create show/hide feature for exercise answers

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#256]
It would be nice to have the ability to show or hide code when we are creating exercises so people can check themselves. By default the code chunk and output would be hidden, and then people could have the option to show the code and output.

1. The `learnr` package is awesome and has this feature, BUT it's running using Shiny and that we cannot do with our current Hugo workflow.

2. R markdown has this feature, but it's specific to HTML output and goes in the header. So, you either show all or hide all by default.

```
---
title: "Habits"
output:
  html_document:
    code_folding: hide
---
```

3. We could use custom JS + CSS to make this happen. [Here's the rough solution I found on Stackoverflow (first answer).](https://stackoverflow.com/questions/37755037/how-to-add-code-folding-to-output-chunks-in-rmarkdown-html-documents) We can adapt this for our own purpose (again, only hide exercise code chunks by default w/ option to expand). I'm also a little unclear on how to get this working with our Hugo. Where should the JS live? How can you use it inside the .Rmd file (same with CSS)?

**Comment by ldecicco-USGS** [comment]
Check out:

https://owi.usgs.gov/blog/LOCAdownscaling/

then go to the blog's rmd to see how it was done, it's not too hard, but I can help if you need it.

**Comment by ldecicco-USGS** [comment]
Also in this one:
https://owi.usgs.gov/blog/plotFlowConc/

**Comment by lindsaycarr** [comment]
WOAH! Had no idea we already did that...oops. Thanks for pointing this out!

**Comment by ldecicco-USGS** [comment]
It's a little putzy...so holler if it's not working. It's hard because knitr doesn't really want to let you put the <div>'s in the output: markdown.

**Comment by lindsaycarr** [comment]
The show/hide is working, it just doesn't look like a button. I put the CSS in there according to https://github.com/USGS-OWI/owi-blog/pull/114/files

**Comment by lindsaycarr** [comment]
Show/Hide feature is working. Checkout #260 and #259 for info on how to use it!
