### ISSUE TITLE
geoknife: double check email language

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#257]
@jiwalker-usgs is going to update how the language in the process status email is worded. We should update the curriculum once that change is in effect.

**Comment by lindsaycarr** [comment]
@jiwalker-usgs any estimated on when/if this happen before the end of FY17?

**Comment by jiwalker-usgs** [comment]
I'll do it now so it makes it into the next release (which should be before end of FY17).

**Comment by lindsaycarr** [comment]
See https://github.com/USGS-R/training-curriculum/pull/162#discussion_r109768446

**Comment by lindsaycarr** [comment]
@jiwalker-usgs keep forgetting where we left off on this - any thoughts?

**Comment by lindsaycarr** [comment]
Closed by #320.
