### ISSUE TITLE
Update training materials summary page

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#288]
The curriculum page (when you click "Home: R Training Curriculum") is out of date. 

_Currently, there is only one course - Introduction to R._ is a very false statement.

**Comment by aappling-usgs** [comment]
So false. Much false.

**Comment by ldecicco-USGS** [comment]
I did update something like that very recently...Ctrl+ F5?

**Comment by aappling-usgs** [comment]
Pretty sure not...https://github.com/USGS-R/training-curriculum/blob/master/themes/hugo_theme_robust/layouts/index.html#L15

**Comment by ldecicco-USGS** [comment]
Oh, I wiped out that language on one of those non-Hugo pages. It's still in the "R Training Curriculum" page. We don't actually link there as obviously as before though, so that's good. Only really on that sidebar.

**Comment by lindsaycarr** [comment]
Yeah, we noticed this when Alison setup the local server to look at my PR.

**Comment by ldecicco-USGS** [comment]
Our internet is soooo bad today...I submitted that last comment seconds after my first comment...but it just showed up 2 minutes after Alisons....
