### ISSUE TITLE
share sbtools lesson with Tim Quinn

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#291]
@aappling-usgs think this is still necessary?

**Comment by aappling-usgs** [comment]
Not necessary for the training, no, but would be a nice collaborative thing to do. Hi Tim, thought you'd be interested to see how we've presented the package to prospective users. Any feedback would be welcome. We appreciate you adopting this package. stuff like that, just so he's in the loop.

**Comment by lindsaycarr** [comment]
draft message ready

**Comment by lindsaycarr** [comment]
Email sent 9/12 ~ 2:30 pm
