### ISSUE TITLE
dataRetrieval: suggested changes

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/training-curriculum#302]
# Data Discovery

- [x] To keep users from having to jump ahead/back in the tutorial, I think it's important to make sure all statements about features have qualifiers if they are not immediately described. For example, in data discovery, the sentence "Another option is to download the data using` readNWISdata`, and see the first and last available dates of that data with the argument `seriesCatalogOutput=TRUE`." but `readNWISdata` is not described until the next page. I would either delete this sentence, or add "which will be covered in the next section" to the end of the sentence. I'll try to note all of these instances. 

- [x] I suggest remove the following text from data discovery section, and stick more strictly 'discovery' so there is less jumping back and forth between ideas.

> To actually download this data, you can query using our three arguments, `stateCd `+ `siteType `+ `parameterCd`, or by the site numbers from the sites_sc_stream_temp data.frame using `unique(sites_sc_stream_temp[['site_no']])`. Downloading NWIS data will be covered in the next section, `readNWISdata`.

- [x] Suggest adding what you are getting when you call the`whatNWISsites` function (add early to this section) - by showing what `head(sites_sc)` produces and walk through each variable. This sort of sets up the rest of the section - mapping, nrow, etc. Should also do this for 'whatNWISdata'. Maybe for one demonstrate `head()` and the other show `?whatNWISdata` to show values of output.

- [x] Remove: "This argument is also available for `readWQPqw`." It's not clear yet what the difference between `readWQPqw `and `readWQPdata` is, so this just kind of confused me. 

# readNWIS

- [x] Not sure if the tables of help files are necessary. Maybe just remind users they can execute e.g., `?readNWISdata` to find those files. Because we are assuming that the users of these modules have some R experience, it seems like they would easily be able to access/find these.  I could see myself using this training as an extended vignette, so the examples and verbal descriptions are really useful. The tables make the amount of info seem overwhelming. Maybe just stick to the examples? 

- [x] sort of conflicted on the previous point. Instead of the tables, you could include the description from the help file, since the abbreviations are sometimes not intuitive - and the description includes links to more information. 

- [x] In the `readNWISpeak` example, I have no idea what the following statement means: "To see peak flows with incomplete dates, change `convertType ` to `FALSE`." I can see that you get a message when you run that code, but not sure why you would have 'incomplete' dates. Just a data entry error?

# readWQP 

- [x] In mapping the Everglades sites, might be a nice to add a box to the map with `rect(-81.70, 25.08, -80.30, 26.51, col = NA, border = 'red')` to see how the points fit within your query.

# Exercise 1

- [x] For the second part, I used `az.lake.temp.wqp <- readWQPdata(statecode="US:04", siteType="Lake, Reservoir, Impoundment", characteristicName="Temperature, water", querySummary = TRUE)` and got n = 436. Maybe show multiple ways of getting the same answer?

# Exercise 2

- [x] Should be more specific about what variable to summarize, which is discharge. I also find all of the parameter code tables really difficult to use. Can we somewhere show how to query these easily? (maybe I missed something in the data discovery). Even something simple like: 
`params <- parameterCdFile`
`params[grep('discharge', params$parameter_nm, ignore.case = TRUE), ]`

- [x] I really struggled with exercise 2. (maybe this was the point!) I think exercises after Data Discovery could have been useful to cement in those ideas - there is a LOT to take in in these first few sections. My struggles included 1) Is this in WQP or NWIS? (go re-read intro section - maybe this is only because I'm new to USGS data) 2) what is meant by 'streamflow' -- discharge? 3) go with discharge, need to find parameter code -- tables are long and difficult to look through so write grep function to find them. I think overall this made me understand things better (good!) but felt it should have been slightly easier given I had just read all that material. I think talking more about easy ways to find parameter codes (in data discovery) and being more specific about what variable you were asking for would simplify this exercise.

# Exercise 3

- [x] Not clear 1) what type of phosphorus to summarize and 2) if I should calculate whether, per lake, the max value of all P observations occured in Jan 1992, or across all lakes in MN measured in 1992 for phosphorus, which had the maximum P value (which I think is a clearer way to ask the question). Figured out it was the latter but only after cheating and looking at the answer ;)

**Comment by lindsaycarr** [comment]
Yeah, I felt like the tables were awesome but looking back now it was super helpful as I was still trying to figure out the best way to organize the information, but just adds a lot of extra stuff that is available elsewhere.

**Comment by lindsaycarr** [comment]
Closed by #316
