### ISSUE TITLE
geoknife: suggested changes

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/training-curriculum#306]
## Accessible data

- [x] It's noted that users can upload their own shape files to GDP but that they will be wiped frequently. Can you explain when you want to choose this option? Just to do your task, and save output?

## Exercise 3

- [x] Just a note: I got a slightly different answer. My result from July 4 was `29.66275` using the following code: 
`tx_fabric <- webdata(all_webdata['TopoWx: Topoclimatic Daily Air Temperature Dataset for the Conterminous United States'],
                     variables = 'tmax',
                     times = as.POSIXct(c('2007-07-04 01:00:00', '2007-07-04 23:00:00')))`
`tx_stencil <- webgeom('state::Texas')`
`tx_geojob <- geoknife(tx_stencil, tx_fabric)`
`tx_results <- result(tx_geojob)`

**Comment by lindsaycarr** [comment]
The slightly different answer is likely from our differing times - my time range includes 2 more hours than yours: `as.POSIXct(c("2007-07-04 12:01", "2007-07-05 11:59"), tz = "UTC")`

**Comment by lindsaycarr** [comment]
Closed by #316
