### ISSUE TITLE
geoknife: suggested editorial changes

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/training-curriculum#307]
## Accessible Data

~- [ ] In Delaware example, there is commented code not being recognized as a comment (also one in the stencil section.~ being taken care of with styling in #303, #304, and #312

- [x] UNIWISC - not sure what this abbreviation is?

## Construct Calls

~- [ ] many code comments not being recognized as comments~ being taken care of with styling in #303, #304, and #312
- [x] This part is confusing in the 'wait' section: "you can tell the job to wait to continue when defining your knife". Should this be " you can tell the job to wait when defining your knife"?

**Comment by lindsaycarr** [comment]
Closed by #316
