### ISSUE TITLE
sbtools: suggested editorial changes

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/training-curriculum#308]
## Introduction

- [x] "In this lesson, will teach how to interact with ScienceBase" to "In this lesson, you will learn how to interact with ScienceBase".

## Data Discovery
- [x] (in code comment) "# search using a contributors name" to "# search using a contributor's name" 

~- some code comments not being recognized as comments.~ being taken care of with styling in #303, #304, and #312

## sbitems

- [x] Not sure what an IPDS code is.

## Download Data

- [x] I had to look up the definition of tuple. Maybe change to "ordered set of values". 

~- Some code comments not being recognized as comments~ being taken care of with styling in #303, #304, and #312

## Modify sbitems

Even though there are a lot of "this is a known error in sbtools" notes, this section was still easy to understand and I think is useful even with the current bugs.

**Comment by lindsaycarr** [comment]
Closed by #316
