### ISSUE TITLE
sbtools: suggested edits

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/training-curriculum#309]
## Data Discovery

~- [ ] `query_sb_spatial` examples not returning any results. Is this correct?~ it's a bug in `sbtools`, see #270

## sbitems

- [x] in the "Additional item descriptions" section, there is only one type of identifier listed in the differential heating link. Not sure what this example is supposed to show?
- [x] I found the "Additional item descriptions" to be a little confusing. It made more sense to me in the context of the item identifiers query in the next lesson (Download Data). I suggested moving the additional item descriptions to the next section where you use the `item_exists` function.

## Exercise 1

- [x] Just a note that I got a different answer with the same code (11 returned items vs your 15). I guess this is feasible with data changes, but I would expect there to be more and not less data through time?

**Comment by lindsaycarr** [comment]
@limnoliver could you try logging in and seeing what Exercise 1 returns? I get 15 again, and it might be that you are not logged in. If so, I'll add a note.

**Comment by limnoliver** [comment]
@lindsaycarr yep - logging in fixed this and the code now returns 15 items. Is this because you have different access if you are logged in to SB?

**Comment by lindsaycarr** [comment]
Yep, some of the items are "private" which means you need to be logged in to use them. Thanks for verifying! I will add a little note about that.

**Comment by lindsaycarr** [comment]
Closed by #316
