### ISSUE TITLE
images from figure/ folder not showing up in posts

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#32]
From A:

![image](https://cloud.githubusercontent.com/assets/13220910/17117557/284c09fc-5282-11e6-8336-f51431ef811e.png)

**Comment by ldecicco-USGS** [comment]
I think all the `fig.path="static/Introduction/"` need to now be:
`fig.path="intro-curriculum/static/Introduction/"`

Make sense?

**Comment by ldecicco-USGS** [comment]
Actually in that particular example, those are paths to images (not generated from R)...and I don't see any of those figures pushed to github. You might not need to do what I said then in my previous comment....I don't know...adding these folders will really complicate paths, so you have to be really careful.

**Comment by lindsaycarr** [comment]
I added that so that the plots rendered from code would show up, but yeah still struggling for things from the figure/ folder to show.

**Comment by lindsaycarr** [comment]
Fixed by #45
