### ISSUE TITLE
 Failed to parse date '<nil>' in page course_specific_links.md

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/training-curriculum#40]
ERROR: 2016/07/26 06:57:01 page.go:555: Failed to parse date '<nil>' in page course_specific_links.md

It's not updating on dev because of the above message

**Comment by lindsaycarr** [comment]
Hmmm maybe it's because there's a date in the .md but not in the .Rmd

**Comment by lindsaycarr** [comment]
Strange because the .Rmd on my fork has a date https://github.com/lindsaycarr/intro-curriculum/blob/master/content/course_specific_links.Rmd

**Comment by ldecicco-USGS** [comment]
I'm guessing it's because the "slug" is empty....

**Comment by lindsaycarr** [comment]
Closed with #42
