### ISSUE TITLE
Blog styles

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/training-curriculum#43]
@mwernimont can you copy over the same css you added this morning to the blog post to this repo? 

These are the USGS-OWI/blog pull requests:
PR#71
PR#70
PR#69

**Comment by ldecicco-USGS** [comment]
So I merged the code style, but we'll still want to shorten up the "notecards".

**Comment by mwernimont** [comment]
@ldecicco-USGS #46 Takes care of this
