### ISSUE TITLE
collapsible menus on sidebar

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#50]
Can we get the _Introduction to R Course_ and the _Course Specific Materials_ parents be collapsible menus? This would happen in `sidebar.html`, but I can't seem to figure it out.

**Comment by mwernimont** [comment]
So I'm confused, where do you see these in the sidebar?

**Comment by lindsaycarr** [comment]
Sorry - the PR that's open right now has to be merged first. Should have written that down

**Comment by lindsaycarr** [comment]
@mwernimont you should be good now, #49 has been merged

**Comment by mwernimont** [comment]
So you want the two list items on the left to be collapsable?

**Comment by lindsaycarr** [comment]
Nope, those to things in the menu on the right: 

![image](https://cloud.githubusercontent.com/assets/13220910/17186703/e5c574da-53fb-11e6-97e7-ab13ec60da63.png)

**Comment by mwernimont** [comment]
I'll see what I can do

**Comment by lindsaycarr** [comment]
it works!
