### ISSUE TITLE
Training -> Course Specific link wrong

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/training-curriculum#62]
On the prod drop-down banner it's wrong

On the sidebar, it's correct.

Right:
https://owi.usgs.gov/R/training-curriculum/course-specific-material/

Wrong:
https://owi.usgs.gov/R/training-curriculum/course-specific-links

**Comment by lindsaycarr** [comment]
Yep - Marty is fixing with #61

**Comment by lindsaycarr** [comment]
(well I just wrote found that and added it there as an issue at the same time you made this)
