### ISSUE TITLE
template for this diff from blogs

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-R/training-curriculum#89]
USGSmarkdowntemplates needs different header template

**Comment by lindsaycarr** [comment]
DUE YESTERDAY!

**Comment by wdwatkins** [comment]
😁 https://github.com/USGS-R/USGSmarkdowntemplates/pull/10

**Comment by lindsaycarr** [comment]
Changes for USGSmarkdowntemplates:
- https://github.com/USGS-R/USGSmarkdowntemplates/pull/10
- https://github.com/USGS-R/USGSmarkdowntemplates/pull/12
- https://github.com/USGS-R/USGSmarkdowntemplates/pull/13
- https://github.com/USGS-R/USGSmarkdowntemplates/pull/14

Changes for training-curriculum:
- #90 
- #91
